language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: 
  - pip install coveralls
script: 
  - py.test -v -r f 
  #- coverage run --source=home manage.py test home
after_success:
  - coveralls
